import json
import re
from pathlib import Path

base = Path('/root/ai-seduced.com')
langs = ['fr','de','es','it','pt','nl','pl','ru','tr','ja','kr','hi']

# Traductions pour les 3 FAQ manquantes
trans = {
    "fr": {
        "How do credits work, and do they expire?": "Comment fonctionnent les crédits et expirent-ils ?",
        "Can I train my own AI model using my photos?": "Puis-je entraîner mon propre modèle IA avec mes photos ?",
        "Can I make money with AI Seduced?": "Puis-je gagner de l'argent avec AI Seduced ?",
        "credits_answer": "Les crédits sont la monnaie interne utilisée pour générer du contenu sur AI Seduced. Chaque forfait inclut une allocation mensuelle — 100 crédits pour Basic, 300 pour Pro, 750 pour Platinum et 3 000 pour Diamond. Une génération d'image standard coûte environ 1 crédit, bien que les modèles HD, les extensions avancées ou les prompts complexes puissent en consommer 2 à 5. La génération vidéo coûte plus de crédits que la génération d'images. Important : les crédits non utilisés n'expirent pas lors du renouvellement de votre abonnement — ils se reportent tant que votre compte reste actif. Les recharges sont des packs de crédits supplémentaires inclus automatiquement avec les forfaits Pro et supérieurs (30 recharges/mois sur Pro, 75 sur Platinum, illimité sur Diamond) que vous pouvez réclamer lorsque votre allocation principale est faible. Un abonnement actif est requis pour accéder à toutes les fonctionnalités.",
        "train_answer": "Oui — AI Seduced propose une fonctionnalité d'entraînement de modèle propriétaire qui est l'une des capacités les plus avancées de la plateforme et que très peu de concurrents offrent. Vous pouvez télécharger un ensemble de vos propres photos pour créer un modèle IA personnalisé qui génère du contenu avec votre ressemblance (ou celle d'une personne consentante). Le processus d'entraînement est un module complémentaire payant à partir de 60–65 USD et nécessite plusieurs photos claires pour de meilleurs résultats. Une fois votre modèle personnalisé entraîné, il peut être appliqué à n'importe quel scénario, pose, tenue ou environnement disponible via le système d'extensions. Vous pouvez garder votre modèle entraîné privé pour un usage personnel, ou le publier publiquement et le monétiser — en gagnant des revenus chaque fois que d'autres utilisateurs de la plateforme génèrent des images avec votre personne IA.",
        "money_answer": "Oui — AI Seduced inclut un système de monétisation intégré pour les créateurs. Il existe deux options principales : le modèle d'abonnement de la plateforme, où vous publiez un profil de modèle IA monétisé et gagnez 50 % de chaque vente d'abonnement et de chaque renouvellement des utilisateurs qui s'abonnent à votre contenu ; et la vérification de modèle commercial (10,00 $), qui donne accès à quatre images d'aperçu sur la page de générations pour un usage commercial. Pour monétiser, vous créez un profil de modèle détaillé, téléchargez des images d'entraînement sur la page « Entraînez votre IA », sélectionnez l'option « monétisé » et soumettez pour révision. Une fois approuvé, les abonnés peuvent générer des images avec votre modèle IA directement sur la plateforme. Vous pouvez également promouvoir votre profil de modèle sur les réseaux sociaux pour développer votre base d'abonnés. Les modèles européens doivent obtenir un numéro de TVA pour la conformité légale avec les réglementations de l'UE."
    },
    "de": {
        "How do credits work, and do they expire?": "Wie funktionieren Credits und verfallen sie?",
        "Can I train my own AI model using my photos?": "Kann ich mein eigenes KI-Modell mit meinen Fotos trainieren?",
        "Can I make money with AI Seduced?": "Kann ich mit AI Seduced Geld verdienen?",
        "credits_answer": "Credits sind die interne Währung zur Generierung von Inhalten auf AI Seduced. Jeder Plan enthält eine monatliche Zuteilung — 100 Credits bei Basic, 300 bei Pro, 750 bei Platinum und 3.000 bei Diamond. Eine standardmäßige Bildgenerierung kostet in der Regel etwa 1 Credit, obwohl HD-Modelle, erweiterte Erweiterungen oder komplexe Prompts 2–5 Credits verbrauchen können. Videogenerierung kostet mehr Credits als Bildgenerierung. Wichtig: Ungenutzte Credits verfallen nicht bei Verlängerung Ihres Abonnements — sie werden übertragen, solange Ihr Konto aktiv bleibt. Nachfüllungen sind zusätzliche Credit-Bundles, die automatisch in Pro- und höheren Plänen enthalten sind (30 Nachfüllungen/Monat bei Pro, 75 bei Platinum, unbegrenzt bei Diamond), die Sie beanspruchen können, wenn Ihre Hauptzuteilung niedrig ist. Ein aktiver Abonnementstatus ist für den kontinuierlichen Zugriff auf alle Funktionen erforderlich.",
        "train_answer": "Ja — AI Seduced bietet eine proprietäre Modelltraining-Funktion, die eine der fortschrittlichsten Funktionen der Plattform ist und die nur sehr wenige Mitbewerber anbieten. Sie können einen Satz Ihrer eigenen Fotos hochladen, um ein personalisiertes KI-Modell zu erstellen, das Inhalte mit Ihrem Ähnlichkeitsmerkmal (oder dem einer einwilligenden Person) generiert. Der Trainingsprozess ist ein kostenpflichtiges Add-on ab 60–65 USD und erfordert mehrere klare Fotos für beste Ergebnisse. Sobald Ihr benutzerdefiniertes Modell trainiert ist, kann es auf jedes Szenario, jede Pose, jedes Outfit oder jede Umgebung angewendet werden, die über das Erweiterungssystem verfügbar ist. Sie können Ihr trainiertes Modell für den persönlichen Gebrauch privat halten oder es optional öffentlich veröffentlichen und monetarisieren — mit Einnahmen jedes Mal, wenn andere Plattformnutzer Bilder mit Ihrer KI-Persona generieren.",
        "money_answer": "Ja — AI Seduced enthält ein integriertes Monetarisierungssystem für Ersteller. Es gibt zwei Hauptoptionen: das Abonnementmodell der Plattform, bei dem Sie ein monetarisiertes KI-Modellprofil veröffentlichen und 50 % jedes Abonnementverkaufs und jeder erneuten Abrechnung von Nutzern verdienen, die Ihren Inhalt abonnieren; und die kommerzielle Modellverifizierung (10,00 $), die Zugriff auf vier Vorschaubilder auf der Generierungsseite für kommerzielle Nutzung gewährt. Um zu monetarisieren, erstellen Sie ein detailliertes Modellprofil, laden Trainingsbilder auf die Seite 'Trainiere deine KI' hoch, wählen die Option 'monetarisiert' und reichen sie zur Überprüfung ein. Nach Genehmigung können Abonnenten Bilder mit Ihrem KI-Modell direkt auf der Plattform generieren. Sie können Ihr Modellprofil auch in sozialen Medien bewerben, um Ihre Abonnentenbasis zu vergrößern. Europäische Modelle müssen eine USt-ID für die rechtliche Konformität mit EU-Vorschriften erhalten."
    },
    "es": {
        "How do credits work, and do they expire?": "¿Cómo funcionan los créditos y expiran?",
        "Can I train my own AI model using my photos?": "¿Puedo entrenar mi propio modelo de IA con mis fotos?",
        "Can I make money with AI Seduced?": "¿Puedo ganar dinero con AI Seduced?",
        "credits_answer": "Los créditos son la moneda interna utilizada para generar contenido en AI Seduced. Cada plan incluye una asignación mensual — 100 créditos en Basic, 300 en Pro, 750 en Platinum y 3.000 en Diamond. Una generación de imagen estándar suele costar aproximadamente 1 crédito, aunque los modelos HD, las extensiones avanzadas o los prompts complejos pueden consumir 2–5 créditos. La generación de video cuesta más créditos que la generación de imágenes. Importante: los créditos no utilizados no expiran cuando se renueva su suscripción — se acumulan mientras su cuenta permanezca activa. Las recargas son paquetes de créditos adicionales incluidos automáticamente con los planes Pro y superiores (30 recargas/mes en Pro, 75 en Platinum, ilimitadas en Diamond) que puede reclamar cuando su asignación principal sea baja. Se requiere una suscripción activa para acceder a todas las funciones.",
        "train_answer": "Sí — AI Seduced ofrece una función de entrenamiento de modelos propietaria que es una de las capacidades más avanzadas de la plataforma y que muy pocos competidores ofrecen. Puede subir un conjunto de sus propias fotos para crear un modelo de IA personalizado que genere contenido con su semejanza (o la de una persona que consiente). El proceso de entrenamiento es un complemento de pago desde 60–65 USD y requiere varias fotos claras para obtener los mejores resultados. Una vez entrenado su modelo personalizado, puede aplicarse a cualquier escenario, pose, atuendo o entorno disponible a través del sistema de extensiones. Puede mantener su modelo entrenado privado para uso personal, o publicarlo públicamente y monetizarlo — ganando ingresos cada vez que otros usuarios de la plataforma generen imágenes usando su personaje de IA.",
        "money_answer": "Sí — AI Seduced incluye un sistema de monetización integrado para creadores. Hay dos opciones principales: el modelo de suscripción de la plataforma, donde publica un perfil de modelo de IA monetizado y gana el 50 % de cada venta de suscripción y de cada refacturación de usuarios que se suscriben a su contenido; y la verificación de modelo comercial (10,00 $), que otorga acceso a cuatro imágenes de vista previa en la página de generaciones para uso comercial. Para monetizar, crea un perfil de modelo detallado, sube imágenes de entrenamiento a la página 'Entrena tu IA', selecciona la opción 'monetizado' y envíalo para revisión. Una vez aprobado, los suscriptores pueden generar imágenes usando su modelo de IA directamente en la plataforma. También puede promocionar su perfil de modelo en redes sociales para aumentar su base de suscriptores. Los modelos europeos deben obtener un ID de IVA para el cumplimiento legal con las regulaciones de la UE."
    },
    "it": {
        "How do credits work, and do they expire?": "Come funzionano i crediti e scadono?",
        "Can I train my own AI model using my photos?": "Posso addestrare il mio modello di IA con le mie foto?",
        "Can I make money with AI Seduced?": "Posso guadagnare con AI Seduced?",
        "credits_answer": "I crediti sono la valuta interna utilizzata per generare contenuti su AI Seduced. Ogni piano include un'allocazione mensile — 100 crediti su Basic, 300 su Pro, 750 su Platinum e 3.000 su Diamond. Una generazione di immagini standard costa tipicamente circa 1 credito, anche se i modelli HD, le estensioni avanzate o i prompt ad alta complessità possono consumare 2–5 crediti. La generazione video costa più crediti della generazione di immagini. Importante: i crediti non utilizzati non scadono al rinnovo dell'abbonamento — si accumulano finché il tuo account rimane attivo. Le ricariche sono bundle di crediti aggiuntivi inclusi automaticamente con i piani Pro e superiori (30 ricariche/mese su Pro, 75 su Platinum, illimitate su Diamond) che puoi richiedere quando la tua allocazione principale è bassa. È richiesto uno stato di abbonamento attivo per accedere a tutte le funzionalità.",
        "train_answer": "Sì — AI Seduced offre una funzione di addestramento modello proprietaria che è una delle capacità più avanzate della piattaforma e che pochissimi concorrenti offrono. Puoi caricare un set delle tue foto per creare un modello di IA personalizzato che generi contenuti con la tua somiglianza (o quella di un soggetto consenziente). Il processo di addestramento è un componente aggiuntivo a pagamento a partire da 60–65 USD e richiede più foto chiare per i migliori risultati. Una volta addestrato il tuo modello personalizzato, può essere applicato a qualsiasi scenario, posa, outfit o ambiente disponibile attraverso il sistema di estensioni. Puoi mantenere il tuo modello addestrato privato per uso personale, o opzionalmente pubblicarlo pubblicamente e monetizzarlo — guadagnando entrate ogni volta che altri utenti della piattaforma generano immagini usando la tua persona IA.",
        "money_answer": "Sì — AI Seduced include un sistema di monetizzazione integrato per i creatori. Ci sono due opzioni principali: il modello di abbonamento della piattaforma, dove pubblichi un profilo modello di IA monetizzato e guadagni il 50 % di ogni vendita di abbonamento e riaddebito da parte degli utenti che si abbonano ai tuoi contenuti; e la verifica modello commerciale (10,00 $), che concede accesso a quattro immagini di anteprima sulla pagina delle generazioni per uso commerciale. Per monetizzare, crei un profilo modello dettagliato, carichi le immagini di addestramento sulla pagina 'Addestra la tua IA', selezioni l'opzione 'monetizzato' e invii per la revisione. Una volta approvato, gli abbonati possono generare immagini usando il tuo modello di IA direttamente sulla piattaforma. Puoi anche promuovere il tuo profilo modello sui social media per far crescere la tua base di abbonati. I modelli europei devono ottenere una partita IVA per la conformità legale con le normative UE."
    },
    "pt": {
        "How do credits work, and do they expire?": "Como funcionam os créditos e eles expiram?",
        "Can I train my own AI model using my photos?": "Posso treinar meu próprio modelo de IA com minhas fotos?",
        "Can I make money with AI Seduced?": "Posso ganhar dinheiro com o AI Seduced?",
        "credits_answer": "Os créditos são a moeda interna usada para gerar conteúdo no AI Seduced. Cada plano inclui uma alocação mensal — 100 créditos no Basic, 300 no Pro, 750 no Platinum e 3.000 no Diamond. Uma geração de imagem padrão normalmente custa aproximadamente 1 crédito, embora modelos HD, extensões avançadas ou prompts de alta complexidade possam consumir 2–5 créditos. A geração de vídeo custa mais créditos do que a geração de imagens. Importante: os créditos não utilizados não expiram quando sua assinatura é renovada — eles se acumulam enquanto sua conta permanecer ativa. As recargas são pacotes de créditos adicionais incluídos automaticamente com os planos Pro e superiores (30 recargas/mês no Pro, 75 no Platinum, ilimitadas no Diamond) que você pode reivindicar quando sua alocação principal estiver baixa. É necessário um status de assinatura ativa para acessar todos os recursos.",
        "train_answer": "Sim — o AI Seduced oferece um recurso de treinamento de modelo proprietário que é uma das capacidades mais avançadas da plataforma e que muito poucos concorrentes oferecem. Você pode fazer upload de um conjunto de suas próprias fotos para criar um modelo de IA personalizado que gera conteúdo com sua semelhança (ou a de um sujeito consentiente). O processo de treinamento é um complemento pago a partir de 60–65 USD e requer várias fotos claras para obter os melhores resultados. Depois que seu modelo personalizado for treinado, ele pode ser aplicado a qualquer cenário, pose, roupa ou ambiente disponível através do sistema de extensões. Você pode manter seu modelo treinado privado para uso pessoal, ou opcionalmente publicá-lo publicamente e monetizá-lo — ganhando receita sempre que outros usuários da plataforma gerarem imagens usando sua persona de IA.",
        "money_answer": "Sim — o AI Seduced inclui um sistema de monetização integrado para criadores. Existem duas opções principais: o modelo de assinatura da plataforma, onde você publica um perfil de modelo de IA monetizado e ganha 50 % de cada venda de assinatura e refaturamento de usuários que se inscrevem no seu conteúdo; e a verificação de modelo comercial (10,00 $), que concede acesso a quatro imagens de visualização na página de gerações para uso comercial. Para monetizar, você cria um perfil de modelo detalhado, faz upload de imagens de treinamento na página 'Treine sua IA', seleciona a opção 'monetizado' e envia para revisão. Uma vez aprovado, os assinantes podem gerar imagens usando seu modelo de IA diretamente na plataforma. Você também pode promover seu perfil de modelo nas redes sociais para aumentar sua base de assinantes. Modelos europeus devem obter um ID de IVA para conformidade legal com os regulamentos da UE."
    },
    "nl": {
        "How do credits work, and do they expire?": "Hoe werken credits en vervallen ze?",
        "Can I train my own AI model using my photos?": "Kan ik mijn eigen AI-model trainen met mijn foto's?",
        "Can I make money with AI Seduced?": "Kan ik geld verdienen met AI Seduced?",
        "credits_answer": "Credits zijn de interne valuta die wordt gebruikt om inhoud te genereren op AI Seduced. Elk plan bevat een maandelijkse toewijzing — 100 credits bij Basic, 300 bij Pro, 750 bij Platinum en 3.000 bij Diamond. Een standaard beeldgeneratie kost doorgaans ongeveer 1 credit, hoewel HD-modellen, geavanceerde extensies of complexe prompts 2–5 credits kunnen verbruiken. Videogeneratie kost meer credits dan beeldgeneratie. Belangrijk: ongebruikte credits vervallen niet bij verlenging van je abonnement — ze worden overgedragen zolang je account actief blijft. Navullingen zijn extra credit-bundels die automatisch zijn inbegrepen bij Pro- en hogere plannen (30 navullingen/maand bij Pro, 75 bij Platinum, onbeperkt bij Diamond) die je kunt claimen wanneer je hoofdtoewijzing laag is. Een actief abonnementsstatus is vereist voor continued toegang tot alle functies.",
        "train_answer": "Ja — AI Seduced biedt een eigen modeltrainingsfunctie die een van de meest geavanceerde mogelijkheden van het platform is en die zeer weinig concurrenten bieden. Je kunt een set van je eigen foto's uploaden om een gepersonaliseerd AI-model te maken dat inhoud genereert met je gelijkenis (of die van een toestemmend onderwerp). Het trainingsproces is een betaalde add-on vanaf 60–65 USD en vereist meerdere duidelijke foto's voor de beste resultaten. Zodra je aangepaste model is getraind, kan het worden toegepast op elk scenario, pose, outfit of omgeving die beschikbaar is via het extensiesysteem. Je kunt je getrainde model privé houden voor persoonlijk gebruik, of het optioneel openbaar publiceren en monetariseren — met inkomsten elke keer dat andere platformgebruikers afbeeldingen genereren met je AI-persona.",
        "money_answer": "Ja — AI Seduced bevat een ingebouwd monetariseringssysteem voor makers. Er zijn twee hoofdopties: het abonnementsmodel van het platform, waar je een gemonetariseerd AI-modelprofiel publiceert en 50 % verdient van elke abonnementsverkoop en herfacturering van gebruikers die zich abonneren op je inhoud; en commerciële modelverificatie ($ 10,00), die toegang geeft tot vier voorbeeldafbeeldingen op de generatiepagina voor commercieel gebruik. Om te monetariseren, maak je een gedetailleerd modelprofiel, upload je trainingsafbeeldingen naar de pagina 'Train je AI', selecteer je de optie 'gemonetariseerd' en dien je deze in voor beoordeling. Na goedkeuring kunnen abonnees afbeeldingen genereren met je AI-model rechtstreeks op het platform. Je kunt je modelprofiel ook op sociale media promoten om je abonneebasis te laten groeien. Europese modellen moeten een BTW-nummer verkrijgen voor juridische naleving van EU-regelgeving."
    },
    "pl": {
        "How do credits work, and do they expire?": "Jak działają kredyty i czy wygasają?",
        "Can I train my own AI model using my photos?": "Czy mogę wytrenować własny model AI za pomocą moich zdjęć?",
        "Can I make money with AI Seduced?": "Czy mogę zarabiać na AI Seduced?",
        "credits_answer": "Kredyty to wewnętrzna waluta używana do generowania treści na AI Seduced. Każdy plan zawiera miesięczny przydział — 100 kredytów w Basic, 300 w Pro, 750 w Platinum i 3 000 w Diamond. Standardowe generowanie obrazu zazwyczaj kosztuje około 1 kredytu, choć modele HD, zaawansowane rozszerzenia lub złożone prompty mogą zużywać 2–5 kredytów. Generowanie wideo kosztuje więcej kredytów niż generowanie obrazów. Ważne: niewykorzystane kredyty nie wygasają przy odnowieniu subskrypcji — przechodzą na kolejny okres, dopóki Twoje konto pozostaje aktywne. Uzupełnienia to dodatkowe pakiety kredytów automatycznie uwzględnione w planach Pro i wyższych (30 uzupełnień/miesiąc w Pro, 75 w Platinum, nieograniczone w Diamond), które możesz odebrać, gdy Twój główny przydział jest niski. Aktywny status subskrypcji jest wymagany do ciągłego dostępu do wszystkich funkcji.",
        "train_answer": "Tak — AI Seduced oferuje własną funkcję treningu modelu, która jest jedną z najbardziej zaawansowanych możliwości platformy i którą oferuje bardzo niewielu konkurentów. Możesz przesłać zestaw własnych zdjęć, aby stworzyć spersonalizowany model AI generujący treści z Twoim podobieństwem (lub podobieństwem osoby wyrażającej zgodę). Proces treningu to płatny dodatek od 60–65 USD i wymaga kilku wyraźnych zdjęć dla najlepszych wyników. Po wytrenowaniu Twojego niestandardowego modelu można go zastosować do dowolnego scenariusza, pozy, stroju lub środowiska dostępnego za pośrednictwem systemu rozszerzeń. Możesz zachować swój wytrenowany model jako prywatny do użytku osobistego lub opublikować go publicznie i zmonetyzować — zarabiając przychód za każdym razem, gdy inni użytkownicy platformy generują obrazy za pomocą Twojej osoby AI.",
        "money_answer": "Tak — AI Seduced zawiera wbudowany system monetyzacji dla twórców. Są dwie główne opcje: model subskrypcji platformy, w którym publikujesz zmonetyzowany profil modelu AI i zarabiasz 50 % z każdej sprzedaży subskrypcji i ponownego obciążenia od użytkowników subskrybujących Twoje treści; oraz weryfikacja modelu komercyjnego (10,00 $), która zapewnia dostęp do czterech obrazów podglądu na stronie generowania do użytku komercyjnego. Aby zmonetyzować, tworzysz szczegółowy profil modelu, przesyłasz zdjęcia treningowe na stronę 'Wytrenuj swoje AI', wybierasz opcję 'zmonetyzowane' i przesyłasz do przeglądu. Po zatwierdzeniu subskrybenci mogą generować obrazy za pomocą Twojego modelu AI bezpośrednio na platformie. Możesz również promować swój profil modelu w mediach społecznościowych, aby powiększyć bazę subskrybentów. Modele europejskie muszą uzyskać numer VAT dla zgodności prawnej z przepisami UE."
    },
    "ru": {
        "How do credits work, and do they expire?": "Как работают кредиты и истекают ли они?",
        "Can I train my own AI model using my photos?": "Могу ли я обучить свою собственную модель ИИ на своих фотографиях?",
        "Can I make money with AI Seduced?": "Могу ли я зарабатывать на AI Seduced?",
        "credits_answer": "Кредиты — это внутренняя валюта, используемая для генерации контента на AI Seduced. Каждый план включает ежемесячное выделение — 100 кредитов в Basic, 300 в Pro, 750 в Platinum и 3 000 в Diamond. Одна стандартная генерация изображения обычно стоит примерно 1 кредит, хотя HD-модели, расширенные расширения или сложные промпты могут потреблять 2–5 кредитов. Генерация видео стоит больше кредитов, чем генерация изображений. Важно: неиспользованные кредиты не истекают при продлении подписки — они переносятся, пока ваша учетная запись остается активной. Пополнения — это дополнительные пакеты кредитов, автоматически включенные в планы Pro и выше (30 пополнений/месяц в Pro, 75 в Platinum, безлимитно в Diamond), которые вы можете получить, когда ваше основное выделение заканчивается. Для постоянного доступа ко всем функциям требуется активный статус подписки.",
        "train_answer": "Да — AI Seduced предлагает собственную функцию обучения модели, которая является одной из самых продвинутых возможностей платформы и которую предлагают очень немногие конкуренты. Вы можете загрузить набор своих собственных фотографий, чтобы создать персонализированную модель ИИ, генерирующую контент с вашим сходством (или сходством дающего согласие субъекта). Процесс обучения — это платное дополнение от 60–65 USD и требует нескольких четких фотографий для достижения наилучших результатов. После обучения вашей пользовательской модели ее можно применить к любому сценарию, позе, наряду или окружению, доступному через систему расширений. Вы можете сохранить свою обученную модель в частном порядке для личного использования или опубликовать ее публично и монетизировать — получая доход каждый раз, когда другие пользователи платформы генерируют изображения с использованием вашего ИИ-персонажа.",
        "money_answer": "Да — AI Seduced включает встроенную систему монетизации для создателей. Есть два основных варианта: модель подписки платформы, где вы публикуете монетизированный профиль модели ИИ и получаете 50 % от каждой продажи подписки и повторного списания от пользователей, подписавшихся на ваш контент; и коммерческая верификация модели (10,00 $), предоставляющая доступ к четырем изображениям предпросмотра на странице генераций для коммерческого использования. Для монетизации вы создаете подробный профиль модели, загружаете обучающие изображения на страницу 'Обучите свой ИИ', выбираете опцию 'монетизировано' и отправляете на рассмотрение. После одобрения подписчики могут генерировать изображения с использованием вашей модели ИИ прямо на платформе. Вы также можете продвигать свой профиль модели в социальных сетях, чтобы увеличить свою базу подписчиков. Европейские модели должны получить идентификационный номер НДС для юридического соответствия нормам ЕС."
    },
    "tr": {
        "How do credits work, and do they expire?": "Krediler nasıl çalışır ve sona erer mi?",
        "Can I train my own AI model using my photos?": "Kendi fotoğraflarımı kullanarak kendi AI modelimi eğitebilir miyim?",
        "Can I make money with AI Seduced?": "AI Seduced ile para kazanabilir miyim?",
        "credits_answer": "Krediler, AI Seduced'de içerik oluşturmak için kullanılan iç platform para birimidir. Her plan aylık bir tahsisat içerir — Basic'te 100 kredi, Pro'da 300, Platinum'da 750 ve Diamond'da 3.000. Standart bir görüntü oluşturma genellikle yaklaşık 1 krediye mal olur, ancak HD modelleri, gelişmiş uzantılar veya yüksek karmaşıklıktaki istemler 2–5 kredi tüketebilir. Video oluşturma, görüntü oluşturmaya göre daha fazla krediye mal olur. Önemli: kullanılmayan krediler aboneliğiniz yenilendiğinde sona ermez — hesabınız aktif kaldığı sürece devrederler. Yenilemeler, Pro ve daha yüksek planlarda otomatik olarak dahil edilen ek kredi paketleridir (Pro'da ayda 30 yenileme, Platinum'da 75, Diamond'da sınırsız). Ana tahsisatınız düşük olduğunda talep edebilirsiniz. Tüm özelliklere sürekli erişim için aktif bir abonelik durumu gerekir.",
        "train_answer": "Evet — AI Seduced, platformun en gelişmiş yeteneklerinden biri olan ve çok az rakibin sunduğu özel bir model eğitim özelliği sunar. Kendi benzerliğinizi (veya rıza gösteren bir kişinin benzerliğini) içeren içerikler oluşturan kişiselleştirilmiş bir AI modeli oluşturmak için kendi fotoğraflarınızdan oluşan bir set yükleyebilirsiniz. Eğitim süreci, 60–65 USD'den başlayan ücretli bir eklentidir ve en iyi sonuçlar için birden fazla net fotoğraf gerektirir. Özel modeliniz eğitildikten sonra, uzantı sistemi aracılığıyla mevcut olan herhangi bir senaryo, poz, kıyafet veya sahne ortamına uygulanabilir. Eğitilmiş modelinizi kişisel kullanım için özel tutabilir veya isteğe bağlı olarak herkese açık olarak yayınlayabilir ve para kazanabilirsiniz — platformun diğer kullanıcıları sizin AI kişiliğinizi kullanarak görüntü oluşturduklarında gelir elde edersiniz.",
        "money_answer": "Evet — AI Seduced, içerik oluşturucular için yerleşik bir para kazanma sistemi içerir. İki ana seçenek vardır: platformun abonelik modeli, burada para kazanılabilir bir AI modeli profili yayınlarsınız ve içeriğinize abone olan kullanıcılardan her abonelik satışının ve yeniden faturalamanın %50'sini kazanırsınız; ve ticari model doğrulaması (10,00 $), ticari kullanım için oluşturma sayfasında dört önizleme görüntüsüne erişim sağlar. Para kazanmak için ayrıntılı bir model profili oluşturursunuz, eğitim görüntülerini 'AI'nizi Eğitin' sayfasına yükler, 'para kazanılabilir' seçeneğini belirler ve inceleme için gönderirsiniz. Onaylandıktan sonra aboneler, AI modelinizi doğrudan platformda kullanarak görüntü oluşturabilir. Abone tabanınızı büyütmek için model profilinizi sosyal medyada da tanıtabilirsiniz. Avrupalı modellerin AB düzenlemeleriyle yasal uyumluluk için bir KDV kimliği edinmesi gerekir."
    },
    "ja": {
        "How do credits work, and do they expire?": "クレジットの仕組みと有効期限について教えてください",
        "Can I train my own AI model using my photos?": "自分の写真を使って独自のAIモデルをトレーニングできますか？",
        "Can I make money with AI Seduced?": "AI Seducedでお金を稼げますか？",
        "credits_answer": "クレジットは、AI Seducedでコンテンツを生成するために使用されるプラットフォーム内通貨です。各プランには月次割り当てが含まれています — Basicで100クレジット、Proで300、Platinumで750、Diamondで3,000です。標準的な画像生成は通常約1クレジットかかりますが、HDモデル、高度な拡張機能、または高複雑性のプロンプトは2〜5クレジットを消費する場合があります。動画生成は画像生成よりも多くのクレジットを消費します。重要：未使用のクレジットはサブスクリプションの更新時に失効しません — アカウントがアクティブな限り繰り越されます。リフィルは、Proおよび上位プランに自動的に含まれる追加のクレジットバンドルです（Proで月30リフィル、Platinumで75、Diamondで無制限）。メインの割り当てが少なくなったときに請求できます。すべての機能に継続してアクセスするには、アクティブなサブスクリプション状態が必要です。",
        "train_answer": "はい — AI Seducedは、プラットフォームで最も高度な機能の1つであり、非常に少ない競合他社が提供している独自のモデルトレーニング機能を提供しています。自分の写真のセットをアップロードして、あなたの似顔絵（または同意した被写体の似顔絵）を特徴とするコンテンツを生成するパーソナライズされたAIモデルを作成できます。トレーニングプロセスは60〜65 USDからの有料アドオンであり、最良の結果を得るには複数の鮮明な写真が必要です。カスタムモデルのトレーニングが完了すると、拡張システムを通じて利用可能なあらゆるシナリオ、ポーズ、衣装、シーン環境に適用できます。トレーニング済みモデルを個人使用のために非公開にすることも、オプションで公開して収益化することもできます — 他のプラットフォームユーザーがあなたのAIペルソナを使用して画像を生成するたびに収入を得られます。",
        "money_answer": "はい — AI Seducedには、クリエイターのための組み込み収益化システムが含まれています。主に2つのオプションがあります：プラットフォームのサブスクリプションモデルでは、収益化されたAIモデルプロフィールを公開し、コンテンツにサブスクライブしたユーザーからの各サブスクリプション販売と再請求の50％を獲得します。商用モデル認証（10.00ドル）では、商用利用のために生成ページの4つのプレビュー画像へのアクセスが許可されます。収益化するには、詳細なモデルプロフィールを作成し、トレーニング画像を「AIをトレーニング」ページにアップロードし、「収益化」オプションを選択して審査に提出します。承認後、サブスクライバーはプラットフォーム上で直接AIモデルを使用して画像を生成できます。ソーシャルメディアでモデルプロフィールを宣伝して、サブスクライバーベースを拡大することもできます。欧州のモデルは、EU規制の法的順守のためにVAT IDを取得する必要があります。"
    },
    "kr": {
        "How do credits work, and do they expire?": "크레딧은 어떻게 작동하며 만료되나요?",
        "Can I train my own AI model using my photos?": "내 사진을 사용하여 자체 AI 모델을 훈련시킬 수 있나요?",
        "Can I make money with AI Seduced?": "AI Seduced로 돈을 벌 수 있나요?",
        "credits_answer": "크레딧은 AI Seduced에서 콘텐츠를 생성하는 데 사용되는 플랫폼 내 통화입니다. 각 플랜에는 월간 할당량이 포함됩니다 — Basic은 100크레딧, Pro는 300, Platinum은 750, Diamond은 3,000입니다. 표준 이미지 생성은 일반적으로 약 1크레딧이 소요되지만, HD 모델, 고급 확장 기능 또는 고복잡도 프롬프트는 2–5크레딧을 소모할 수 있습니다. 비디오 생성은 이미지 생성보다 더 많은 크레딧이 필요합니다. 중요: 사용하지 않은 크레딧은 구독 갱신 시 만료되지 않습니다 — 계정이 활성 상태인 한 이월됩니다. 리필은 Pro 및 상위 플랜에 자동으로 포함된 추가 크레딧 번들입니다(Pro는 월 30리필, Platinum은 75, Diamond은 무제한). 주 할당량이 부족할 때 청구할 수 있습니다. 모든 기능에 지속적으로 액세스하려면 활성 구독 상태가 필요합니다.",
        "train_answer": "예 — AI Seduced는 플랫폼에서 가장 고급 기능 중 하나이며 매우 적은 경쟁사가 제공하는 자체 모델 훈련 기능을 제공합니다. 자신의 사진 세트를 업로드하여 자신의 모습(또는 동의한 대상의 모습)을 특징으로 하는 콘텐츠를 생성하는 맞춤형 AI 모델을 만들 수 있습니다. 훈련 과정은 60–65 USD부터 시작하는 유료 추가 기능이며 최상의 결과를 위해 여러 장의 선명한 사진이 필요합니다. 맞춤형 모델 훈련이 완료되면 확장 시스템을 통해 사용 가능한 모든 시나리오, 포즈, 의상 또는 장면 환경에 적용할 수 있습니다. 훈련된 모델을 개인용으로 비공개로 유지하거나 선택적으로 공개적으로 게시하고 수익화할 수 있습니다 — 다른 플랫폼 사용자가 귀하의 AI 페르소나를 사용하여 이미지를 생성할 때마다 수익을 얻습니다.",
        "money_answer": "예 — AI Seduced에는 크리에이터를 위한 내장 수익화 시스템이 포함되어 있습니다. 두 가지 주요 옵션이 있습니다: 플랫폼의 구독 모델에서는 수익화된 AI 모델 프로필을 게시하고 콘텐츠를 구독하는 사용자의 각 구독 판매 및 재청구의 50%를 획득합니다. 상업용 모델 인증($10.00)은 상업용으로 생성 페이지의 4개 미리보기 이미지에 대한 액세스를 부여합니다. 수익화하려면 상세한 모델 프로필을 만들고, 훈련 이미지를 'AI 훈련' 페이지에 업로드하고, '수익화' 옵션을 선택하여 검토를 위해 제출합니다. 승인 후 구독자는 플랫폼에서 직접 AI 모델을 사용하여 이미지를 생성할 수 있습니다. 소셜 미디어에서 모델 프로필을 홍보하여 구독자 기반을 성장시킬 수도 있습니다. 유럽 모델은 EU 규정의 법적 준수를 위해 VAT ID를 취득해야 합니다."
    },
    "hi": {
        "How do credits work, and do they expire?": "क्रेडिट कैसे काम करते हैं और क्या वे समाप्त हो जाते हैं?",
        "Can I train my own AI model using my photos?": "क्या मैं अपनी फोटो का उपयोग करके अपना खुद का AI मॉडल प्रशिक्षित कर सकता हूँ?",
        "Can I make money with AI Seduced?": "क्या मैं AI Seduced से पैसे कमा सकता हूँ?",
        "credits_answer": "क्रेडिट AI Seduced पर सामग्री जनरेट करने के लिए उपयोग की जाने वाली प्लेटफॉर्म-आंतरिक मुद्रा हैं। प्रत्येक योजना में एक मासिक आवंटन शामिल है — Basic पर 100 क्रेडिट, Pro पर 300, Platinum पर 750, और Diamond पर 3,000। एक मानक छवि जनरेशन में आमतौर पर लगभग 1 क्रेडिट लगता है, हालांकि HD मॉडल, उन्नत एक्सटेंशन, या उच्च जटिलता वाले प्रॉम्प्ट 2–5 क्रेडिट का उपभोग कर सकते हैं। वीडियो जनरेशन में छवि जनरेशन की तुलना में अधिक क्रेडिट लगते हैं। महत्वपूर्ण: अप्रयुक्त क्रेडिट आपकी सदस्यता के नवीनीकरण पर समाप्त नहीं होते — जब तक आपका खाता सक्रिय रहता है, वे आगे बढ़ते रहते हैं। रिफिल अतिरिक्त क्रेडिट बंडल हैं जो Pro और उच्चतर योजनाओं में स्वचालित रूप से शामिल हैं (Pro पर 30 रिफिल/माह, Platinum पर 75, Diamond पर असीमित) जिन्हें आप अपने मुख्य आवंटन कम होने पर दावा कर सकते हैं। सभी सुविधाओं तक निरंतर पहुँच के लिए सक्रिय सदस्यता स्थिति आवश्यक है।",
        "train_answer": "हाँ — AI Seduced एक मालिकाना मॉडल प्रशिक्षण सुविधा प्रदान करता है जो प्लेटफॉर्म की सबसे उन्नत क्षमताओं में से एक है और बहुत कम प्रतिस्पर्धी इसे प्रदान करते हैं। आप अपनी स्वयं की तस्वीरों का एक सेट अपलोड कर सकते हैं ताकि एक व्यक्तिगत AI मॉडल बनाया जा सके जो आपकी समानता (या सहमति देने वाले विषय की समानता) को दर्शाती सामग्री उत्पन्न करता हो। प्रशिक्षण प्रक्रिया एक सशुल्क ऐड-ऑन है जो 60–65 USD से शुरू होता है और सर्वोत्तम परिणामों के लिए कई स्पष्ट तस्वीरों की आवश्यकता होती है। एक बार जब आपका कस्टम मॉडल प्रशिक्षित हो जाता है, तो इसे एक्सटेंशन सिस्टम के माध्यम से उपलब्ध किसी भी परिदृश्य, मुद्रा, पोशाक या दृश्य वातावरण पर लागू किया जा सकता है। आप अपने प्रशिक्षित मॉडल को व्यक्तिगत उपयोग के लिए निजी रख सकते हैं, या वैकल्पिक रूप से इसे सार्वजनिक रूप से प्रकाशित और मुद्रीकृत कर सकते हैं — हर बार जब अन्य प्लेटफॉर्म उपयोगकर्ता आपके AI व्यक्तित्व का उपयोग करके छवियाँ उत्पन्न करते हैं तो राजस्व अर्जित कर सकते हैं।",
        "money_answer": "हाँ — AI Seduced में निर्माताओं के लिए एक अंतर्निहित मुद्रीकरण प्रणाली शामिल है। दो मुख्य विकल्प हैं: प्लेटफॉर्म की सदस्यता मॉडल, जहाँ आप एक मुद्रीकृत AI मॉडल प्रोफाइल प्रकाशित करते हैं और अपनी सामग्री की सदस्यता लेने वाले उपयोगकर्ताओं से प्रत्येक सदस्यता बिक्री और पुनर्बिलिंग का 50% अर्जित करते हैं; और वाणिज्यिक मॉडल सत्यापन ($10.00), जो वाणिज्यिक उपयोग के लिए जनरेशन पृष्ठ पर चार पूर्वावलोकन छवियों तक पहुँच प्रदान करता है। मुद्रीकृत करने के लिए, आप एक विस्तृत मॉडल प्रोफाइल बनाते हैं, प्रशिक्षण छवियों को 'अपने AI को प्रशिक्षित करें' पृष्ठ पर अपलोड करते हैं, 'मुद्रीकृत' विकल्प चुनते हैं और समीक्षा के लिए सबमिट करते हैं। स्वीकृत होने पर, सदस्य सीधे प्लेटफॉर्म पर आपके AI मॉडल का उपयोग करके छवियाँ उत्पन्न कर सकते हैं। आप अपने ग्राहक आधार को बढ़ाने के लिए सोशल मीडिया पर अपनी मॉडल प्रोफाइल का प्रचार भी कर सकते हैं। यूरोपीय मॉडलों को EU विनियमों के साथ कानूनी अनुपालन के लिए एक VAT ID प्राप्त करना होगा।"
    }
}

# Appliquer les traductions
for lang in langs:
    path = base / lang / 'index.html'
    if not path.exists():
        print(f"{lang}: FICHIER MANQUANT")
        continue
    html = path.read_text(encoding='utf-8')
    original = html
    
    t = trans[lang]
    
    # Remplacer les 3 questions
    html = html.replace(
        "How do credits work, and do they expire?",
        t["How do credits work, and do they expire?"]
    )
    html = html.replace(
        "Can I train my own AI model using my photos?",
        t["Can I train my own AI model using my photos?"]
    )
    html = html.replace(
        "Can I make money with AI Seduced?",
        t["Can I make money with AI Seduced?"]
    )
    
    # Remplacer les réponses (on cherche les paragraphes EN spécifiques)
    # Pour les réponses, on va chercher le texte brut dans les <p> des faq-answer
    
    # Credits answer
    en_credits = "Credits are the in-platform currency used to generate content on AI Seduced. Each plan comes with a monthly allocation"
    if en_credits in html:
        # Extraire tout le paragraphe
        m = re.search(r'(<p>)' + re.escape(en_credits) + r'.*?(</p>)', html, re.DOTALL)
        if m:
            html = html.replace(m.group(0), '<p>' + t["credits_answer"] + '</p>')
    
    # Train answer
    en_train = "Yes — AI Seduced offers a proprietary model training feature"
    if en_train in html:
        m = re.search(r'(<p>)' + re.escape(en_train) + r'.*?(</p>)', html, re.DOTALL)
        if m:
            html = html.replace(m.group(0), '<p>' + t["train_answer"] + '</p>')
    
    # Money answer
    en_money = "Yes — AI Seduced includes a built-in monetization system"
    if en_money in html:
        m = re.search(r'(<p>)' + re.escape(en_money) + r'.*?(</p>)', html, re.DOTALL)
        if m:
            html = html.replace(m.group(0), '<p>' + t["money_answer"] + '</p>')
    
    if html != original:
        path.write_text(html, encoding='utf-8')
        print(f"{lang}: ✓ 3 FAQ traduites")
    else:
        print(f"{lang}: ✗ Aucun changement")

print("\nTerminé!")
